services:

  dawn_bot_1_10:
    build: .
    image: dawn-bot
    container_name: dawn_bot_container_1_50
    volumes:
      - ./config/data/accounts_1_50.yaml:/app/config/data/accounts.yaml
    working_dir: /app
    command: ["python", "run.py", "-module=farm"]
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
